### ISSUE TITLE
ImportError: cannot import name 'FromOriginalControlnetMixin' from 'diffusers.loaders'

### ISSUE THREAD

**Issue by meng-yuan321** [NJU-PCALab/AddSR#14]
I download the diffusers source code from https://github.com/huggingface/diffusers/tree/main/src/diffusers, and replace the original 'scheduling_ddpm.py' file with [this](https://github.com/NJU-PCALab/AddSR/blob/main/utils/scheduling_ddpm.py, but  there are other errors: 
![image](https://github.com/NJU-PCALab/AddSR/assets/73415049/3beb9e90-3f9b-4d5c-8954-c1ee98ff1832)

**Comment by CSRuiXie** [comment]
The error may be caused by using the wrong version of diffusers. The version of diffusers should be 0.21.0
