### ISSUE TITLE
Right way to setup pretrained weights?

### ISSUE THREAD

**Issue by ppriyank** [NJU-PCALab/AddSR#17]
[pipelines/pipeline_addsr.py](https://github.com/NJU-PCALab/AddSR/blob/main/pipelines/pipeline_addsr.py#L57)
[test_addsr.py](https://github.com/NJU-PCALab/AddSR/blob/main/test_addsr.py#L120)

This weight  "/home/amax/workspace/ruixie/SeeSR/preset/ram_swin_large_14m.pth"
I downloaded it from the website directly, but it's not mentioned in the Readme: https://huggingface.co/spaces/xinyu1205/recognize-anything/blob/main/ram_swin_large_14m.pth

was it supposed to be set differently?

Additionally, ([ram/models/utils.py](https://github.com/NJU-PCALab/AddSR/blob/main/ram/models/utils.py#L131))

```
tokenizer = BertTokenizer.from_pretrained('/home/amax/workspace/ruixie/SeeSR/ram/bert')
```
what would be the right path for this

**Comment by CSRuiXie** [comment]
We have provided the download link for the 'ram_swin_large_14m.pth' file [here](https://github.com/NJU-PCALab/AddSR?tab=readme-ov-file#-train) in the Readme. It is the same as the one you have downloaded. Additionally, you can download the BERT weights from [here](https://drive.google.com/file/d/1DkUiVpVGHIZulDSCu9PPlSnegJlz833W/view?usp=drive_link).

**Comment by ppriyank** [comment]
gotcha, thanks
