### ISSUE TITLE
No matching distribution found for mc==0.0

### ISSUE THREAD

**Issue by LeoJiaPlus** [NJU-PCALab/AddSR#2]
When I installed the requirements,got this error.
ERROR: Could not find a version that satisfies the requirement mc==0.0 (from versions: none)
ERROR: No matching distribution found for mc==0.0

**Comment by CSRuiXie** [comment]
Sorry for the mistake. We have rectified the ‘requirements.txt’ file, so now you should be able to successfully install the requirements.
