### ISSUE TITLE
AttributeError: 'DDPMScheduler' object has no attribute 'get_z0'

### ISSUE THREAD

**Issue by ziyizhetutanota** [NJU-PCALab/AddSR#3]
DDPM has no funtion get_z0, it seem to chnage the source codes

**Comment by CSRuiXie** [comment]
You can replace the original 'scheduling_ddpm.py' file with [this](https://github.com/NJU-PCALab/AddSR/blob/main/utils/scheduling_ddpm.py), then it should work.

**Comment by ziyizhetutanota** [comment]
thank you.
Another question, I'd like to ask that your discriminator was trained from scrach or iused a pre-trained model

**Comment by CSRuiXie** [comment]
We train the discriminator  from scrach.

**Comment by ziyizhetutanota** [comment]
Thank you. Can you provide your pretrained discriminator ? I want to finetune my model.

**Comment by CSRuiXie** [comment]
We haven't saved the parameters of the discriminator model, so we can't provide the pre-trained discriminator. Sorry about that.

**Comment by ziyizhetutanota** [comment]
OK，thank you anyway
