### ISSUE TITLE
推理的时候为什么没用CFG呢？

### ISSUE THREAD

**Issue by heart-du** [NJU-PCALab/AddSR#5]

**Comment by CSRuiXie** [comment]
We find that using cfg during inference may introduce the artifacts, which also aligns the settings in [SDXL-Turbo](https://huggingface.co/stabilityai/sdxl-turbo), they set the guidance_scale=0

**Comment by heart-du** [comment]
> We find that using cfg during inference may introduce the artifacts, which also aligns the settings in [SDXL-Turbo](https://huggingface.co/stabilityai/sdxl-turbo), they set the guidance_scale=0

可是ADD在训练的时候是把CFG蒸馏到学术模型中去了，AddSR似乎并没有，但是效果却也很好，挺奇怪。

**Comment by CSRuiXie** [comment]
I'm not sure if the ADD paper mentions whether the teacher model uses CFG.  Could you please tell me the specific location?

**Comment by heart-du** [comment]
我看别人复现的ADD代码里面有

**Comment by CVRS-CJH** [comment]
> 我看别人复现的ADD代码里面有

请问有别人复现的ADD代码吗，可否发个链接，谢谢
