### ISSUE TITLE
/home/amax/workspace/ruixie/SeeSR/ram/bert

### ISSUE THREAD

**Issue by MingdongHe** [NJU-PCALab/AddSR#7]
![image](https://github.com/NJU-PCALab/AddSR/assets/46629149/3f1b8445-31d2-4f51-b377-e568867854d1)
it seems need a bert model pre_weight? how to play? thanks

**Comment by CSRuiXie** [comment]
You can download from [HERE](https://drive.google.com/file/d/1DkUiVpVGHIZulDSCu9PPlSnegJlz833W/view?usp=drive_link), then rectifying the path and it should work.
